//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telegram", Namespace="http://schemas.datacontract.org/2004/07/SensateIoT.SmartEnergy.Dsmr.Parser.DTO")]
    [System.SerializableAttribute()]
    public partial class Telegram : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentTariffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.EnergyData EnergyDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GasConsumptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.PowerData PowerDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentTariff {
            get {
                return this.CurrentTariffField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentTariffField, value) != true)) {
                    this.CurrentTariffField = value;
                    this.RaisePropertyChanged("CurrentTariff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.EnergyData EnergyData {
            get {
                return this.EnergyDataField;
            }
            set {
                if ((object.ReferenceEquals(this.EnergyDataField, value) != true)) {
                    this.EnergyDataField = value;
                    this.RaisePropertyChanged("EnergyData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GasConsumption {
            get {
                return this.GasConsumptionField;
            }
            set {
                if ((this.GasConsumptionField.Equals(value) != true)) {
                    this.GasConsumptionField = value;
                    this.RaisePropertyChanged("GasConsumption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.PowerData PowerData {
            get {
                return this.PowerDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PowerDataField, value) != true)) {
                    this.PowerDataField = value;
                    this.RaisePropertyChanged("PowerData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnergyData", Namespace="http://schemas.datacontract.org/2004/07/SensateIoT.SmartEnergy.Dsmr.Parser.DTO")]
    [System.SerializableAttribute()]
    public partial class EnergyData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EnergyConsumptionTariff1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EnergyConsumptionTariff2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EnergyProductionTariff1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EnergyProductionTariff2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EnergyConsumptionTariff1 {
            get {
                return this.EnergyConsumptionTariff1Field;
            }
            set {
                if ((this.EnergyConsumptionTariff1Field.Equals(value) != true)) {
                    this.EnergyConsumptionTariff1Field = value;
                    this.RaisePropertyChanged("EnergyConsumptionTariff1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EnergyConsumptionTariff2 {
            get {
                return this.EnergyConsumptionTariff2Field;
            }
            set {
                if ((this.EnergyConsumptionTariff2Field.Equals(value) != true)) {
                    this.EnergyConsumptionTariff2Field = value;
                    this.RaisePropertyChanged("EnergyConsumptionTariff2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EnergyProductionTariff1 {
            get {
                return this.EnergyProductionTariff1Field;
            }
            set {
                if ((this.EnergyProductionTariff1Field.Equals(value) != true)) {
                    this.EnergyProductionTariff1Field = value;
                    this.RaisePropertyChanged("EnergyProductionTariff1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EnergyProductionTariff2 {
            get {
                return this.EnergyProductionTariff2Field;
            }
            set {
                if ((this.EnergyProductionTariff2Field.Equals(value) != true)) {
                    this.EnergyProductionTariff2Field = value;
                    this.RaisePropertyChanged("EnergyProductionTariff2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PowerData", Namespace="http://schemas.datacontract.org/2004/07/SensateIoT.SmartEnergy.Dsmr.Parser.DTO")]
    [System.SerializableAttribute()]
    public partial class PowerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InstantaneousCurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InstantaneousPowerProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InstantaneousPowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InstantaneousVoltageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InstantaneousCurrent {
            get {
                return this.InstantaneousCurrentField;
            }
            set {
                if ((this.InstantaneousCurrentField.Equals(value) != true)) {
                    this.InstantaneousCurrentField = value;
                    this.RaisePropertyChanged("InstantaneousCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InstantaneousPowerProduction {
            get {
                return this.InstantaneousPowerProductionField;
            }
            set {
                if ((this.InstantaneousPowerProductionField.Equals(value) != true)) {
                    this.InstantaneousPowerProductionField = value;
                    this.RaisePropertyChanged("InstantaneousPowerProduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InstantaneousPowerUsage {
            get {
                return this.InstantaneousPowerUsageField;
            }
            set {
                if ((this.InstantaneousPowerUsageField.Equals(value) != true)) {
                    this.InstantaneousPowerUsageField = value;
                    this.RaisePropertyChanged("InstantaneousPowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InstantaneousVoltage {
            get {
                return this.InstantaneousVoltageField;
            }
            set {
                if ((this.InstantaneousVoltageField.Equals(value) != true)) {
                    this.InstantaneousVoltageField = value;
                    this.RaisePropertyChanged("InstantaneousVoltage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.Parser.IParserService")]
    public interface IParserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParserService/Parse", ReplyAction="http://tempuri.org/IParserService/ParseResponse")]
        SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.Telegram Parse(string frame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParserService/Parse", ReplyAction="http://tempuri.org/IParserService/ParseResponse")]
        System.Threading.Tasks.Task<SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.Telegram> ParseAsync(string frame);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParserServiceChannel : SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.IParserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParserServiceClient : System.ServiceModel.ClientBase<SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.IParserService>, SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.IParserService {
        
        public ParserServiceClient() {
        }
        
        public ParserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.Telegram Parse(string frame) {
            return base.Channel.Parse(frame);
        }
        
        public System.Threading.Tasks.Task<SensateIoT.SmartEnergy.Dsmr.WebClient.Common.WCF.Parser.Telegram> ParseAsync(string frame) {
            return base.Channel.ParseAsync(frame);
        }
    }
}
